package tiendafrailejones.vista.a_general;


import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import tiendafrailejones.controlador.ControladorLogin;
import tiendafrailejones.modelo.Login;
import tiendafrailejones.modelo.consultas.ConsultaContraseña;
import tiendafrailejones.modelo.consultas.ConsultasLogin;
import tiendafrailejones.utils.AES;
import tiendafrailejones.utils.DataUser;
import tiendafrailejones.vista.b_administrador.b_Menu;
import tiendafrailejones.vista.c_empleado.c_Menu;

public class login extends javax.swing.JFrame {

    private final ConsultasLogin consultasLogin = new ConsultasLogin();
    private final ControladorLogin controladorLogin = new ControladorLogin(consultasLogin);
    private final ConsultaContraseña consultaContraseña = new ConsultaContraseña();
    int value = 0;
    private Login login = new Login();

    public login() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        labelUsuarioOContraseña = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        inputUsuario = new javax.swing.JTextField();
        jLabelInputEmail = new javax.swing.JLabel();
        jLabelInputContraseña = new javax.swing.JLabel();
        inputPassword = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FraileStore");
        setLocationByPlatform(true);
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setName("a_LogIn"); // NOI18N
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setResizable(false);
        setSize(new java.awt.Dimension(1280, 720));

        jPanel2.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));
        jPanel2.setAlignmentX(0.0F);
        jPanel2.setAlignmentY(0.0F);
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.setFocusable(false);
        jPanel2.setMaximumSize(new java.awt.Dimension(960, 720));
        jPanel2.setMinimumSize(new java.awt.Dimension(960, 720));
        jPanel2.setName("INTRO_IMG"); // NOI18N
        jPanel2.setPreferredSize(new java.awt.Dimension(950, 720));
        jPanel2.setRequestFocusEnabled(false);
        jPanel2.setVerifyInputWhenFocusTarget(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 960, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );

        labelUsuarioOContraseña.setForeground(new java.awt.Color(255, 0, 0));

        jLabel1.setBackground(new java.awt.Color(12, 91, 99));
        jLabel1.setText("img_isologo");

        inputUsuario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        inputUsuario.setAlignmentX(0.0F);
        inputUsuario.setAlignmentY(0.0F);
        inputUsuario.setBorder(null);
        inputUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        inputUsuario.setMaximumSize(new java.awt.Dimension(310, 30));
        inputUsuario.setMinimumSize(new java.awt.Dimension(310, 30));
        inputUsuario.setPreferredSize(new java.awt.Dimension(320, 30));
        inputUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputUsuarioActionPerformed(evt);
            }
        });

        jLabelInputEmail.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabelInputEmail.setText("Correo Electrónico");
        jLabelInputEmail.setMaximumSize(new java.awt.Dimension(310, 30));
        jLabelInputEmail.setMinimumSize(new java.awt.Dimension(310, 1));
        jLabelInputEmail.setRequestFocusEnabled(false);

        jLabelInputContraseña.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabelInputContraseña.setText("Contraseña");
        jLabelInputContraseña.setMaximumSize(new java.awt.Dimension(310, 30));
        jLabelInputContraseña.setMinimumSize(new java.awt.Dimension(310, 1));
        jLabelInputContraseña.setRequestFocusEnabled(false);

        inputPassword.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        inputPassword.setAlignmentY(0.0F);
        inputPassword.setBorder(null);
        inputPassword.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        inputPassword.setMaximumSize(new java.awt.Dimension(310, 30));
        inputPassword.setMinimumSize(new java.awt.Dimension(310, 30));
        inputPassword.setPreferredSize(new java.awt.Dimension(320, 30));
        inputPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputPasswordActionPerformed(evt);
            }
        });

        btnLogin.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnLogin.setText("INGRESAR");
        btnLogin.setAlignmentY(0.0F);
        btnLogin.setBorder(null);
        btnLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnLogin.setMaximumSize(new java.awt.Dimension(310, 50));
        btnLogin.setMinimumSize(new java.awt.Dimension(310, 50));
        btnLogin.setPreferredSize(new java.awt.Dimension(320, 30));
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 960, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(labelUsuarioOContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelInputEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(inputPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelInputContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(inputUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelInputEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelInputContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelUsuarioOContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(205, 205, 205))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputUsuarioActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        StringBuilder stringBuilder = new StringBuilder();
        char[] passArray = inputPassword.getPassword();
        stringBuilder.append(passArray);
        String password = stringBuilder.toString();

        String pass = null;
        try {
            pass = AES.singletonAes().encrypt(password);
        } catch (IOException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }

        login.setCorreo(inputUsuario.getText());
        login.setPassword(pass);

        Login loginTmp = controladorLogin.existeUsuario(login);
        if (loginTmp.getCorreo()== null || loginTmp.getPassword() == null) {
            labelUsuarioOContraseña.setText("Usuario o contraseña incorrecto");
        } else {
            DataUser dataUser = DataUser.getDataUser();
            dataUser.setIdUser(String.valueOf(loginTmp.getId()));

            if (loginTmp.getUserType().equals("ADMINISTRADOR")) {
                Boolean check = consultaContraseña.checkPassword(loginTmp.getPassword(), loginTmp);
                if (check) {
                    a_CambioContrasena cambioPassword = new a_CambioContrasena();
                    cambioPassword.setControladorLogin(controladorLogin);
                    cambioPassword.setLogin(loginTmp);
                    cambioPassword.setVisible(true);
                    this.dispose();
                } else {
                    b_Menu adminMenu = new b_Menu();
                    adminMenu.setVisible(true);
                }

                this.dispose();
            } else if (loginTmp.getUserType().equals("EMPLEADO")) {
                Boolean check = consultaContraseña.checkPassword(loginTmp.getPassword(), loginTmp);
                if (check) {
                    a_CambioContrasena cambioPassword = new a_CambioContrasena();
                    cambioPassword.setControladorLogin(controladorLogin);
                    cambioPassword.setLogin(loginTmp);
                    cambioPassword.setVisible(true);
                    this.dispose();
                } else {
                    c_Menu clienteMenu = new c_Menu();
                    clienteMenu.setVisible(true);
                }

                this.dispose();
            }
            labelUsuarioOContraseña.setText("");
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void inputPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputPasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JPasswordField inputPassword;
    private javax.swing.JTextField inputUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelInputContraseña;
    private javax.swing.JLabel jLabelInputEmail;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelUsuarioOContraseña;
    // End of variables declaration//GEN-END:variables
}
